name: fitquest_project
description: "FitQuest - Student Fitness Challenge App built with Flutter and Dart"

publish_to: 'none' # keep this since the app is private

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.2.5
  path: ^1.8.3
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image.png